### ISSUE TITLE
Mask

### ISSUE THREAD

**Issue by ayoggchen** [earhian/Humpback-Whale-Identification-1st-#1]
Can you explain more exactly what the mask is? THANKS.

**Comment by earhian** [comment]
semantic segmentation of whale :)

**Comment by liaopeiyuan** [comment]
During the competition, someone on the Kaggle forum released a dataset of hand annotated masks that separated whales from the background. We used those predictions to train a U-net that is then applied to the entire train+test set. This serves as a 4th channel input in addition to the RGB image.
