### ISSUE TITLE
'senet154' pretrained model needs input_channel=3, but your model's input is 4. and I can't find the transformation between the input channel.How you do that ?

### ISSUE THREAD

**Issue by Bigwode** [earhian/Humpback-Whale-Identification-1st-#6]
'senet154' model pretrained on imagenet needs input_channel=3, but your model's input is 4. And I can't find the transformation between the input channel.How you do that ?Thanks!

**Comment by earhian** [comment]
I used try-except for loading pretrained model in line 367 of senet.py.

**Comment by Bigwode** [comment]
@earhian Oww, It means that the pretrained weights in the first Conv are not loaded in your model, right?

**Comment by earhian** [comment]
yes!
